apiVersion: v2
name: monitoring-stack
description: for monitoring
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: ">=25.0.0 <26.0.0"
    repository: https://prometheus-community.github.io/helm-charts
